#!/bin/bash
# PreToolUse guard — block dangerous operations

# Fail-open if jq not available
if ! command -v jq &>/dev/null; then
    exit 0
fi

INPUT=$(cat)
TOOL=$(echo "$INPUT" | jq -r '.tool_name // empty' 2>/dev/null) || exit 0

# Guard 1: Block writes to ML model headers (generated files)
if [ "$TOOL" = "Write" ] || [ "$TOOL" = "Edit" ]; then
    FILE=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || exit 0
    if echo "$FILE" | grep -qE '(^|/)models/[^/]*\.h$'; then
        echo "BLOCKED: models/*.h files are generated by emlearn training scripts. Do not edit manually."
        exit 2
    fi
fi

# Guard 2: Block git add -A / --all / .
if [ "$TOOL" = "Bash" ]; then
    CMD=$(echo "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null) || exit 0
    if echo "$CMD" | grep -qE 'git\s+add\s+(-A|--all|\.)(\s|$)'; then
        echo "BLOCKED: Never use 'git add -A', 'git add --all', or 'git add .'. Stage specific files only."
        exit 2
    fi
fi

exit 0
